### ISSUE TITLE
Add timestamp to youtube id

### ISSUE THREAD

**Issue by VAISHALI-DHANOA** [jku-vds-lab/jku-vds-lab.github.io#17]
Add a timestamp parameter to the following:

 file: filename to look for, prefix http://data.jku-vds-lab.at/papers/
```
 - name: 'Talk'
   youtube-id: txxx
   timestamp: 488 // this will be the new parameter
   description: ''
   extraurl: ''
   slides:
    - file: ''
    - file: ''
```

another suggestion

```
 - name: 'Talk'
   youtube-url: [txxx ](https://www.youtube.com/watch?v=t7PVq)// replace youtube-id with youtube-url
   description: ''
   extraurl: ''
   slides:
    - file: ''
    - file: ''
```
